@echo off

:: Set the main file name and archive name
set NAME="document"
set ARCHIVE_NAME="document"
set TITLE="Project Template"
:: Set the Overleaf directory path
set OVERLEAF_DIR="%USERPROFILE%\Dropbox\Apps\Overleaf\%TITLE%"

:: Command line argument handling loop
:loop
IF "%~1"=="" GOTO all
IF "%~1"=="archive" GOTO archive
IF "%~1"=="overleaf" GOTO overleaf
IF "%~1"=="update" GOTO update
IF "%~1"=="remove-comments" GOTO remove-comments
IF "%~1"=="clean" GOTO clean
GOTO loop

:: Compile the LaTeX document and clean auxiliary files
:all
latexmk -pdf %NAME%
latexmk -c
GOTO:EOF

:: Archive the document
:archive
GOTO remove-comments

:: Archive step 2: Create a zip archive excluding certain files
:archive2
zip -u -r --exclude="*.zip" --exclude "*.synctex.gz" --exclude="%NAME%.pdf" --exclude="%NAME%-*.tex" "%ARCHIVE_NAME%.zip" ./
echo "Restore the original document.tex file"
xcopy /Y document-backup.tex document.tex
del /Q document-backup.tex
GOTO:EOF

:: Sync files to Overleaf directory
:overleaf
call %~0 clean
mkdir "%OVERLEAF_DIR%"
xcopy /A /D /E /Y /F * "%OVERLEAF_DIR%" /exclude:exclude.txt 
GOTO:EOF

:: Update the local repository
:update
REM xcopy /A /D /E /Y /F "%OVERLEAF_DIR%\*" .\ /exclude:exclude.txt 
git pull
GOTO:EOF

:: Clean auxiliary files generated by LaTeX
:clean
latexmk -c
del /F *.bbl *.dvi *.log *.bak *.aux *.blg *.idx *.ps *.toc *.out *.snm *.nav *.xml *.bcf *.spl *.synctex.gz *~ *.aux *.blg *.fdb_latexmk *.fls *.log*.synctex* *-blx.bib
REM rmdir /s /q tikz-cache
echo "Junk files removed"
GOTO:EOF

:: Remove comments from the main LaTeX file
:: Requires sed for Windows @ https://github.com/mbuilov/sed-windows
:remove-comments
xcopy /Y /F document.tex document-backup.tex*
latexpand --empty-comments document.tex --output document-stripped.tex
sed -i "/^\s*%%/d" document-stripped.tex
xcopy /Y /F document-stripped.tex document.tex*
del /F document-stripped.tex
echo "Comments in document.tex removed. See the original file document-backup.tex"
IF "%~1"=="archive" GOTO archive2
GOTO:EOF
