# Original: https://bpaulino.com/entries/10-automating-your-work-with-github-actions

# This is the name of our workflow.
# Github will show it on its Website UI
name: "Generate GitHub Pages"
# This configures our workflow to be triggered
# only when we push to the master branch
on:
  push:
    branches:
      - master

# Here is where we define our jobs. 
# Which means the tasks we want Github to execute
jobs:
  build:
    name: "Generate GitHub Pages"
    # Here we specify in which OS we want it to run
    runs-on: ubuntu-18.04
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    # Now we define which actions will take place.
    # One after another
    steps:
      # This is the first action. It will make sure that we have
      # all the necessary files from our repo, including our custom actions
      # This action here is actually from a remote repo available from Github itself
      - uses: actions/checkout@v2
      # This is where we use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: satackey/action-docker-layer-caching@v0.0.8
      # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: ${{ runner.os }}-docker-cache-{hash}
          restore-keys: |
            ${{ runner.os }}-docker-cache-
      # This is our custom action. Here is where we will define our git commands
      # to push our website updates to the `gh-pages` branch.
      # Notice that we are specifying the path to the action here.
      # We will create those files in a sec
      - uses: ./.github/actions/build-site
        env:
          # Now make sure you add this environment variable.
          # This token will allow us to push to github directly
          # without having to type in our password.
          # The GITHUB_TOKEN is available by default
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENCRYPTED_2DB5BEF319F4_KEY: ${{ secrets.ENCRYPTED_2DB5BEF319F4_KEY }}
          ENCRYPTED_2DB5BEF319F4_IV: ${{ secrets.ENCRYPTED_2DB5BEF319F4_IV }}
